Changement request
nat730/back_chef_doeuvre pull request #44
Opened 2024-03-30 18:11 UTC by Zelie-C

Changement enum : kilogramme -> kg et litre -> l
Changement request produit

**Il faut qu'on peuple notre bdd avec d'autres produits et d'autres catégories**

2024-04-02 09:22 UTC, ThomasLaforge requested changes

2024-04-02 09:22 UTC, ThomasLaforge commented on requests/customer.http
> +Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMTUzMzkwMH0.71NyGGGncarz65lXVYf9KEml0v3UVFqBYJXIm7-nDEg
Peut être pas à modifier ça pour l'occase ^^

2024-04-02 09:22 UTC, ThomasLaforge commented on src/router/Orderitem.ts
> +      if (unity_symbol === "kg" || unity_symbol === "l") {
Vous pouvez créer un enum typescript pour ça ^^

2024-04-03 10:17 UTC, nat730 submitted a review, later dismissed

2024-04-03 10:24 UTC, ThomasLaforge approved these changes, later dismissed
Si les enums typescript ne sont pas importants pour vous, vous pouvez merger la PR

2024-04-03 10:27 UTC, Zelie-C commented
Je vais checker les enums avant de merge quand j'aurais un peu de temps :)

2024-04-03 12:50 UTC, ThomasLaforge approved these changes, later dismissed
lvgtm 🚀

2024-04-05 12:59 UTC, nat730 approved these changes
farpait

2024-04-21 10:46 UTC, merged